version: "3"
services:
  bot:
    build: .
    restart: always
    env_file:
      - .env
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - ./database/tables.sql:/docker-entrypoint-initdb.d/1-tables.sql
      - ./database/views.sql:/docker-entrypoint-initdb.d/2-views.sql
      - ./database/triggers.sql:/docker-entrypoint-initdb.d/3-triggers.sql
